# Generated by Django 5.0.4 on 2024-05-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMentalHealth1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_timestamp', models.CharField(blank=True, max_length=19, null=True)),
                ('gender', models.CharField(blank=True, max_length=18, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('course', models.CharField(blank=True, max_length=23, null=True)),
                ('student_year', models.CharField(blank=True, max_length=26, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=18, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=14, null=True)),
                ('depression', models.CharField(blank=True, max_length=23, null=True)),
                ('anxiety', models.CharField(blank=True, max_length=20, null=True)),
                ('panic_attack', models.CharField(blank=True, max_length=25, null=True)),
                ('treatment', models.CharField(blank=True, max_length=44, null=True)),
            ],
            options={
                'db_table': 'student_mental_health_1',
                'managed': False,
            },
        ),
    ]
