# Generated by Django 4.2.11 on 2024-05-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0002_studentmentalhealth1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMentalHealth1',
        ),
    ]
